### PR TITLE
Implements sia codes CL,OP, solves ZO bug for wireless PIR.

### PR DESCRIPTION
**Pull request by crallian**
Made imports within the class relative to easier be used as custom_component.
Added SIA codes CL, OP that is sent instead of CG, OG if only one area is used in SPC.
Set last_changed_by='N/A' for area partset, beacuse the last partset user is not provided by SPC.
Force Zone open if sia_code = ZO, to solve problem with some wireless zones reporting open for 0 duration that led to no status change registration.

### CODE REVIEW

**Comment by crallian** [comment]
@mbrrg 
Trying to describe what the different changes do, and where you find them for easier review:

"Made imports within the class relative instead of absolute to easier be used as custom_component and make changes."
- The imports in the beginning of area.py and zone.py

"Added SIA codes CL, OP that is sent instead of CG, OG if only one area is used in SPC."
Solves Issue #2 ,and is described in that issue-thread. In short, if you only use one area and/or (I am not sure) disable areas, SPC send CL/OP instead of CG/OG. In this case no area ID is provided and we have to loop over all areas to update those that have changed.
- All changes in __init__.py is related to this.
- All changes in area.py, except the last 6 lines.

"Set last_changed_by='N/A' for area partset, beacuse the last partset user is not provided by SPC."
Previously, if unset - use last unset-userID, else use last set-userID. The problem is that this gives the wrong userID if the panel is partset. I could not find the partset-userID. I prefer to have N/A instead of a wrong value.
-The last 6 lines in area.py

"Force Zone open if sia_code = ZO, to solve problem with some wireless zones reporting open for 0 duration that led to no status change registration."
-All changes in zone.py

**Comment by mbrrg** [comment]
@crallian I took the liberty to move your modifications to a separate PR and restructure a few things. Would you mind helping me test whether everything still works for you? I haven't been able to reproduce the CL/OG problem (even with one area) on firmware 3.8.5 nor do I have a wireless PIR. https://github.com/mbrrg/pyspcwebgw/tree/various-fixes

**Comment by crallian** [comment]
@mbrrg Wow, great!!! I had a quick look through your changes, and as you say, it seems to do the same things, just more beatiful and simple. :) 
If I remember correctly, the CL/OG issue appears if you have only one area, and then use the possibility to disable the area settings completely (e.g. to minimize the button presses needed on the panel).
I am very happy to test your code, plan to do so in an hour or so, if our small kids sleeps well...

**Comment by jschlyter** [comment]
ping @crallian

**Comment by crallian** [comment]
@jschlyter I am not sure if there are any conflicts/unintended reverses here... seems to be less conflicts than #PR10, but I think that code is mostly better, solving the same things...

**Comment by jschlyter** [comment]
This issue should be addressed by #10

**Pull request closed without merging**
