### PR TITLE
Get change_by_user for PartSet

### PR DESCRIPTION
**Pull request by crallian**
Gets the username for PartSet ('NL') from the SIA message, since this is not provided by the EDP protocol.

### CODE REVIEW

**Comment by crallian** [comment]
@mbrrg I would love to have also this fix merged, if still possible.

**Comment by crallian** [comment]
Added a check so SIA description has expected length 3, since it was found that there is no User/UserID if a "shortcut button" is used for arming.

**Comment by jschlyter** [comment]
Please confirm that this still works as intended

**Comment by crallian** [comment]
@jschlyter Yes, I have been running this PR together with "pyspcwebgw:various-fixes" for a long time, so it should work to merge this.

**Comment by crallian** [comment]
@jschlyter May I ask why this was closed? Prior to the merge of #10 , there was a bug so the wrong partset user was reported.
With the merge of #10 , user N/A will be reported for partset.
This PR provides the actual name of the partset user, by getting it from the ”description” field.

**Comment by jschlyter** [comment]
Sorry, I might have misread the comments. Can you please rebase against `master` ?

**Pull request closed without merging**
